### ISSUE TITLE
add terminal shortcut to Application Launchbar

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#14]

**Comment by thomshaw92** [comment]
so @stebo85 my understanding is that in order to make this work we will need to add the application shortcut in the ubuntu Dockerfile? 

https://lkubaski.wordpress.com/2012/06/29/adding-lxde-start-menu-and-desktop-shortcuts/#:~:text=To%20add%20a%20shortcut%20on,'Add%20to%20desktop'%20option.&text=This%20means%20that%20if%20you,explained%20in%20the%20previous%20chapter.

We could define multiple definitions for the shortcuts...

/itksnap_example_definition.txt

which contains
```
[Desktop Entry] 
Encoding=UTF-8 
Type=Application 
Name=ITKSNAP
Name[en_US]=ITKSNAP\
Exec=bash curl -s -S -X GET https://swift.rc.nectar.org.au:.... singularityImages && git clone https://github.com/CAIsr/transparent-singularity.git itksnap_3.8.0_20200505.sif && apt install git && sudo apt install git && apt update && sudo apt update && sudo apt install git && git clone https://github.com/CAIsr/transparent-singularity.git itksnap_3.8.0_20200505.sif && cd itksnap_3.8.0_20200505.sif/ && ./run_transparent_singularity.sh itksnap_3.8.0_20200505.sif && ./itksnap \
Comment[en_US]=test\
StartupNotify=true" >> ~/.local/share/applications/test.desktop
```
Then add 
```
RUN cp \itksnap_example_definition.txt ~/.local/share/applications/itksnap.desktop
RUN lxpanelctl restart
```
to Dockerfile?
