### ISSUE TITLE
Handle modules at start

### ISSUE THREAD

**Issue by MartinGrignard** [NeuroDesk/vnm#25]
As stated by @stebo85 on mattermost, it would be interesting to make all the terminals source `module.sh` and set the `MODULEPATH` at start thus removing VNM terminal from the applications.

Here is the puppet script he proposes to add inside `/etc/profile`:
```puppet
      ~> file_line { 'source_modules':
        path => '/etc/profile',
        line => 'source /etc/profile.d/modules.sh'
      }
      ~> file_line { 'modulepath':
        path => '/etc/profile',
        line => 'export MODULEPATH=/data/lfs2/CVL/containers/modules'
```
Let's give it a try!

**Comment by MartinGrignard** [comment]
## 1
Addind this:
```shell
source /usr/share/module.sh
export MODULEPATH=/vnm/modules
```
to `/etc/profile` does not work.

## 2
Addind this:
```shell
source /usr/share/module.sh
```
to `/etc/profile` does not work and setting adding the environment variable `MODULEPATH=/vnm/modules` to the dockerfile does not work.

**Comment by stebo85** [comment]
I just started working on this :)

**Comment by stebo85** [comment]
ok, I think I found one problem: 
source /etc/profile
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

source /etc/bash.bashrc 
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Just looking into this error, because I think this is why the settings where not applied

**Comment by stebo85** [comment]
Ok, I added our neuro user to the sudo group (or I could have remove the hint?) this then makes the sourcing work :)
