### ISSUE TITLE
add visual studio code to main image

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#30]

**Comment by MartinGrignard** [comment]
Shouldn't this bé added to thé softwares available in thé form if images? Géré at thé lab WE work with Atom mainly and this means we coule add other tools as modules 😊
This could also apply to the browser, Jupiter, etc

**Comment by kaczmarj** [comment]
i agree with @MartinGrignard. the vnm image should be as small as possible and shouldn't include software that could be packaged separately.

**Comment by MartinGrignard** [comment]
The only issue with this is that we start growing the list of modules we want to propose so we start actually creating a package manager... Maybe we should start thinking about how we want users to actually use vnm 😛
Is this just an hpc oriented solution? Or do we want to provide a full fledged desktop experience? Because providing a bunch of neuroimaging tools is easy, managing a lot of non neuroimaging tools might be out of scope here (IDK)

**Comment by kaczmarj** [comment]
again agree with @MartinGrignard - it would be out of scope in my opinion, and it would also require more and more maintenance, which, sooner or later, would be untenable

**Comment by MartinGrignard** [comment]
But this means we have to clarrify the goal of vnm, what do we want to allow the end user to achieve with it?

Because simply providing neuro imaging tools is great but what does vnm propose that simply using singularity does not?

I'm really scratching my head right now to figure this out 😅

**Comment by kaczmarj** [comment]
one thing that vnm provides over simply using singularity is a familiar GUI experience and an orchestration of containers. Using singularity, one would have to make one very larger container or use many smaller containers on their own (that would be hard for many people, especially container novices). vnm also allows windows and macos users to use the guis of their favorite neuroimaging packages, which are typically written for linux. and singularity right now does not run containers on windows or macos, though that could change in the future.

**Comment by civier** [comment]
Hello all.

Because we cannot nest containers at the moment, so any software that is used to run the scripts that call the singularity containers will have to be installed within the VNM. This include python, visual studio, and full-fledged MATLAB, if we can make it work (some people use MATLAB as their base script language; very poor choice, but this is the way things are).
In addition, software that performs permanent operations in the environment (like sshfs to mount a remote filesystem) will have to be installed within VNM as well.
When we can nest singularity containers, this will be another question -- but does it mean that each singularity container in the library will have to include Singularity within it?
What other software should be included in the base VNM in your opinion?

Oren

**Comment by MartinGrignard** [comment]
Ok I see, so I still believe it would be better packaging all the softwares in separate singularity images but I understand the point of having VS code or matlab.
Let's try adding those and see what we manage to do, because I don't know how to manage the licences for a soft like Matlab which has many versions all being dozens of GB with, for each, packages that you can purchase 😛
It will be fun finding a way around this 😁

**Comment by civier** [comment]
I also wonder what about software that has a python interface rather than command-line interface.
How are we going to put it exactly in a transparent container?
@stebo85, how is it handled in CVL?

**Comment by stebo85** [comment]
great discussion! I agree with everyone I guess :D 

I made a little table here, that could help us making the decision on what to package in containers and what to add to main:
https://github.com/NeuroDesk/vnm/wiki/Add-a-tool-to-VNM

Happy for more input!

I think for VScode it's pretty clear - it should be in main. However, there are already some edge case that we can discuss.

@civier: regarding your python interface question - I think it depends! What software are you thinking of? Can you try to classify it based on the table?

**Comment by civier** [comment]
Amazing work on the table @stebo85 I'm very impressed !!!

Regarding Python software. Let's take for example cmtk that has a Nipype interface (but that would be true to any software with nipype interface, I guess):
https://nipype.readthedocs.io/en/1.1.7/interfaces/generated/interfaces.cmtk/cmtk.html#

I'll follow the columns in the table per Steffen's suggestion:
easy install - ? (I had trouble because it depends on other python packages, but I think now they have it in Anaconda)
coordinates containers - no
small in size - yes
latest version is ok - no
useful for most users - no
Conclusion - container

So the conclusion is container. The only problem is that we cannot put it in a container because it has a Python interface rather than a command line (correct me if wrong). And even if it also had a command-line interface, you'd agree with me that when possible, a python interface is obviously more reliable and easier to use (ideally no input/output files involved; everything is passed through variables).

We have exactly the same problem with Matlab packages like SPM, as there is no way to containarise them. Notice that in Matlab the dependency problem is especially severe given that there is a common search path (and often different packages have the same commands), but to be honest, Matlab packages usually do not depend on each other to begin with (although I can see a problem with packages that depend on different versions of SPM). Did any of you had major issues with dependencies in matlab?

**Comment by stebo85** [comment]
Thank you @civier :)

I agree, I think we should try to put cmtk in a container. I don't think that the python interface is a problem - because this would be outside the container (as nipype has the actual interface - under the hood it is still calling command line tools that would then be inside the container)

For SPM, I would follow neurodockers approach of using compiled SPM and the matlab runtime in a container again (with niype outside the container managing things)

Let's add these tools step by step and see where it breaks :)

**Comment by civier** [comment]
@stebo85, maybe cmtk is not the best example, but let's take something like nilearn that is pure Python (no command-line, as far as I know). What would you do with this?
And in any case, looking into the future, I guess more and more tools would offer python interface (that does not go through a command line under the hood), and we should decide how to include them.
I don't know enough about how the matlab runtime works. When you compile something in Matlab, does it automatically include all dependencies inside? If yes, maybe something similar can be done in python?

**Comment by stebo85** [comment]
@civier, yes nilearn is an interesting one (and I think python in general). I would love to hear what others think about this, but this is my current approach to this: The python world is pretty good in terms of dependency management and reproducing environments (using conda). Also, it's not feasible to package every python module in it's own container. Therefore, I currently install python via miniconda directly on the HPC (and therefore I would vote for miniconda in the main vnm container) and then I handle conflicting dependencies via environments - this allows me to use nipype and slurm/pbs to coordinate neuro software in containers. One downside of this approach is that miniconda creates a lot of files and this can exhaust file count quotas on HPCs. So my conclusion: There should be a python available on the vnm/hpc layer, but I think it also makes sense to package certain python applications if they belong to the workflow you are trying to containerize.

**Comment by MartinGrignard** [comment]
Great discussion here! Indeed packaging python would be tricky and since there are already two versions of python available inside VNM, why not going with those? I've never used conda/miniconda since it creates a big overhead IMO so I only use pip as a dependency manager for my projects. It would make things very easy for people working with python to stick with pip as people could simply provide the `requirements.txt` file and everything would be ok.
For nipype, it should stay in the main image as it depends on cli to access other softwares (containerize nipype would mean adding a new level of containers no?)
So it only makes sense to containerize self contained python apps that do not interact with other packages we could provide in separate containers.

**Comment by kaczmarj** [comment]
@MartinGrignard - one benefit of conda is that they package pre-compiled packages. this is especially helpful when wheels don't exist for a package. traits is a package that needs compiling and doesn't ship a wheel, so conda makes it easier to install. traits is a nipype dependency

**Comment by civier** [comment]
Hello all. I've just been in the OHBM OpenScience rooms, and met Loic Tetrel (@ltetrel)
from NeuroLibre. He told me about these Python encapsulated environments (venv), and I wonder if it's something we can use for packages like nilearn for example?
https://www.liquidweb.com/kb/how-to-setup-a-python-virtual-environment-on-ubuntu-18-04/
It won't be as isolated as a container, but at least something. Thoughts?

**Comment by stebo85** [comment]
Yes to me venv and conda envs achieve the same thing in terms of separation and we should use these. Conda makes some things easier because it provides packages that just run and don't need compilation. Happy with both :)
