### ISSUE TITLE
Add instructions on how to donwload packages and load them through the terminal

### ISSUE THREAD

**Issue by civier** [NeuroDesk/vnm#82]
Is everything should be done through the "module" command? Are you aliasing it to something else?

**Comment by stebo85** [comment]
how do you mean this? The applications get installed when a user clicks on an appliation in the menu and then they can be loaded on the terminal using "module load" - this is documented when a user opens a terminal.

**Comment by civier** [comment]
I see. Can you add this explanation to the README please?

In any case, it will be also nice that the module command will download packages if they are not already downloaded. This way, when a subject runs a script that uses certain packages (the script loading the packages with the module command), the packages will be automatically downloaded.

**Comment by MartinGrignard** [comment]
For now, the `module` command only provides the already installed packages. This makes everything simple and clean. If a module is not installed yet, it should not be available with `module avail` because it would mean that VNM should ship with all the files required to make softwares accessible as modules. The creation of those scripts is automated via transparent singularity. If we decide to make all the package available at start, we have to generate all those files and manage in an other way the download/installation of the modules...

For me it's better to keep things as they are now, people running script should always check if the modules they need are installed before actually running the script anyway.

Tell me if you think this is a bad solution :)

**Comment by stebo85** [comment]
Yes, fully agree with @MartinGrignard - a module load should not install modules because this is not what users expect. 

However, I also think it's great to document how to do this correctly via the command line, which I now did :)

I hope that solves this issues nicely =)
