### ISSUE TITLE
user testing

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/vnm#9]
can everyone try the current master tree and see if things work :?

**Comment by thomshaw92** [comment]
Working on Windows 10 Docker (Powershell) and WSL2 Docker (even though they are the same) :P

**Comment by kaczmarj** [comment]
Works for me on Debian Bullseye (tested in Firefox) and macOS Catalina (10.15.5) (tested in Firefox, Google Chrome, and Safari)

I tested using the Dockerfile in #15

**Comment by MartinGrignard** [comment]
Tested on Ubuntu 20.04 with the build from #15 on firefox and working perfectly!

**Comment by meganEJcampbell** [comment]
I'm am 100% noob so would love to test but not sure exactly what to do... :[

**Comment by stebo85** [comment]
Hi @meganEJcampbell :) That's very valuable feedback!!!! Can you try to follow the instruction here https://github.com/NeuroDesk/vnm and change it when it's not clear :) and ask when things go wrong :) 1000 Thanks for testing !!!!

**Comment by stebo85** [comment]
I started a little matrix in the wiki: 
https://github.com/NeuroDesk/vnm/wiki/VNM-testing

**Comment by meganEJcampbell** [comment]
Thought I'd move thread here @stebo85 given I'm testing on macOS + firefox browser, and the other closed issue topic was something else.
Copy of out previous thread:
@meganEJcampbell - Thank you so much for testing! The glitch you are seeing in ITKsnap is interesting. It's not a connection issue, because the container runs on your own computer. Can you check if there is a warning in the background that blocks you from using itk? I have an idea how to fix this otherwise!

closing the container: Yes, this is not yet userfriendly and you need to press CTRL-C in the terminal where you ran the docker command. Does this give you back the control and can you then type stop?
@meganEJcampbell I hope I fixed the itksnap problems in the current master branch :) Can you test again?

So I've tried again and ITKsnap still looks weird. I've attached screenshots including both my local terminal window and the bash command window on VNM. Is there an example image on there that I can try to open? I tried clicking the link 'download example data' and nothing happened.
![Screen Shot 2020-07-03 at 3 01 32 pm](https://user-images.githubusercontent.com/34408937/86433825-15874f80-bd3f-11ea-9f00-fd6eb943de07.png)
![Screen Shot 2020-07-03 at 3 01 46 pm](https://user-images.githubusercontent.com/34408937/86433832-19b36d00-bd3f-11ea-963e-1e03945f9d75.png)
![Screen Shot 2020-07-03 at 3 01 54 pm](https://user-images.githubusercontent.com/34408937/86433834-1ae49a00-bd3f-11ea-9d2a-20fb18c53a4d.png)

**Comment by stebo85** [comment]
Dear @meganEJcampbell, can you test again the latest version of the vnm container. I fixed the bug and it hopefully now works nicely :) To get the latest version you might have to manually delete the older version beforehand: "docker rmi vnmd/vnm"

**Comment by stebo85** [comment]
closing this issue as everything is done right now - please open separate issues for each new problem so we can split up work better and keep track of problems and status of their solutions :)
